In [1]:
import pandas as pd

In [2]:
testDf = pd.read_csv("WFTest.csv")
trainDf = pd.read_csv("WFTrain.csv")

In [3]:
print(trainDf.columns)
print(testDf.columns)

Index(['TRAN_AMT', 'ACCT_PRE_TRAN_AVAIL_BAL', 'CUST_AGE', 'OPEN_ACCT_CT',
       'WF_dvc_age', 'PWD_UPDT_TS', 'CARR_NAME', 'RGN_NAME', 'STATE_PRVNC_TXT',
       'ALERT_TRGR_CD', 'DVC_TYPE_TXT', 'AUTHC_PRIM_TYPE_CD',
       'AUTHC_SCNDRY_STAT_TXT', 'CUST_ZIP', 'CUST_STATE', 'PH_NUM_UPDT_TS',
       'CUST_SINCE_DT', 'TRAN_TS', 'TRAN_DT', 'ACTN_CD', 'ACTN_INTNL_TXT',
       'TRAN_TYPE_CD', 'ACTVY_DT', 'FRAUD_NONFRAUD'],
      dtype='object')
Index(['dataset_id', 'TRAN_AMT', 'ACCT_PRE_TRAN_AVAIL_BAL', 'CUST_AGE',
       'OPEN_ACCT_CT', 'WF_dvc_age', 'PWD_UPDT_TS', 'CARR_NAME', 'RGN_NAME',
       'STATE_PRVNC_TXT', 'ALERT_TRGR_CD', 'DVC_TYPE_TXT',
       'AUTHC_PRIM_TYPE_CD', 'AUTHC_SCNDRY_STAT_TXT', 'CUST_ZIP', 'CUST_STATE',
       'PH_NUM_UPDT_TS', 'CUST_SINCE_DT', 'TRAN_TS', 'TRAN_DT', 'ACTN_CD',
       'ACTN_INTNL_TXT', 'TRAN_TYPE_CD', 'ACTVY_DT'],
      dtype='object')

In [4]:
testDf['dataset_id']

0          1
1          2
2          3
3          4
4          5
        ...
5995    5996
5996    5997
5997    5998
5998    5999
5999    6000
Name: dataset_id, Length: 6000, dtype: int64

In [5]:
trainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TRAN_AMT                 14000 non-null  float64
 1   ACCT_PRE_TRAN_AVAIL_BAL  14000 non-null  float64
 2   CUST_AGE                 14000 non-null  int64
 3   OPEN_ACCT_CT             14000 non-null  int64
 4   WF_dvc_age               14000 non-null  int64
 5   PWD_UPDT_TS              10875 non-null  object
 6   CARR_NAME                11291 non-null  object
 7   RGN_NAME                 11291 non-null  object
 8   STATE_PRVNC_TXT          11291 non-null  object
 9   ALERT_TRGR_CD            14000 non-null  object
 10  DVC_TYPE_TXT             12239 non-null  object
 11  AUTHC_PRIM_TYPE_CD       14000 non-null  object
 12  AUTHC_SCNDRY_STAT_TXT    13926 non-null  object
 13  CUST_ZIP                 14000 non-null  int64
 14  CUST_STATE               13964 non-null  object
 15  PH_NUM_UPDT_TS           6939 non-null   object
 16  CUST_SINCE_DT            14000 non-null  object
 17  TRAN_TS                  14000 non-null  object
 18  TRAN_DT                  14000 non-null  object
 19  ACTN_CD                  14000 non-null  object
 20  ACTN_INTNL_TXT           14000 non-null  object
 21  TRAN_TYPE_CD             14000 non-null  object
 22  ACTVY_DT                 14000 non-null  object
 23  FRAUD_NONFRAUD           14000 non-null  object
dtypes: float64(2), int64(4), object(18)
memory usage: 2.6+ MB

In [6]:
trainDf.head()

,TRAN_AMT,ACCT_PRE_TRAN_AVAIL_BAL,CUST_AGE,OPEN_ACCT_CT,WF_dvc_age,PWD_UPDT_TS,CARR_NAME,RGN_NAME,STATE_PRVNC_TXT,ALERT_TRGR_CD,...,CUST_STATE,PH_NUM_UPDT_TS,CUST_SINCE_DT,TRAN_TS,TRAN_DT,ACTN_CD,ACTN_INTNL_TXT,TRAN_TYPE_CD,ACTVY_DT,FRAUD_NONFRAUD
0,5.38,23619.91,47,4,2777,1/16/2018 11:3:58,cox communications inc.,southwest,nevada,MOBL,...,NV,2/24/2021 15:55:10,1993-01-06 00:00:00,5/3/2021 18:3:58,5/3/2021,SCHPMT,P2P_COMMIT,P2P,5/3/2021,Non-Fraud
1,65.19,0.00,45,5,2721,NaN,charter communications,southwest,california,MOBL,...,CA,NaN,1971-01-07 00:00:00,1/13/2021 19:19:37,1/13/2021,SCHPMT,P2P_COMMIT,P2P,1/13/2021,Non-Fraud
2,54.84,34570.63,36,8,1531,12/22/2021 10:42:51,utah broadband llc,mountain,utah,ONLN,...,MD,5/5/2019 1:8:39,1994-02-01 00:00:00,4/8/2021 9:42:51,4/8/2021,SCHPMT,P2P_COMMIT,P2P,4/8/2021,Fraud
3,0.01,0.00,62,3,835,2/8/2020 7:28:31,t-mobile usa inc.,southwest,california,MOBL,...,NV,2/16/2019 6:45:37,2001-11-01 00:00:00,8/10/2021 15:28:31,8/10/2021,SCHPMT,P2P_COMMIT,P2P,8/10/2021,Non-Fraud
4,497.08,12725.18,81,2,1095,12/28/2020 12:12:44,cogent communications,south central,texas,MOBL,...,UT,5/8/2020 10:27:6,1987-02-07 00:00:00,6/27/2021 11:12:44,6/27/2021,SCHPMT,P2P_COMMIT,P2P,6/27/2021,Fraud

In [8]:
to_datetime = ['PWD_UPDT_TS', 'PH_NUM_UPDT_TS', 'CUST_SINCE_DT','TRAN_TS',
               'TRAN_DT', 'ACTVY_DT']
for datetime in to_datetime:
  trainDf[datetime] = pd.to_datetime(trainDf[datetime], errors='coerce')
  #We're ignoring errors because some issues exist in time (June 31 in one of the columns!)
  #Coercing these values turns them into NaT (not a time)
trainDf.head()

,TRAN_AMT,ACCT_PRE_TRAN_AVAIL_BAL,CUST_AGE,OPEN_ACCT_CT,WF_dvc_age,PWD_UPDT_TS,CARR_NAME,RGN_NAME,STATE_PRVNC_TXT,ALERT_TRGR_CD,...,CUST_STATE,PH_NUM_UPDT_TS,CUST_SINCE_DT,TRAN_TS,TRAN_DT,ACTN_CD,ACTN_INTNL_TXT,TRAN_TYPE_CD,ACTVY_DT,FRAUD_NONFRAUD
0,5.38,23619.91,47,4,2777,2018-01-16 11:03:58,cox communications inc.,southwest,nevada,MOBL,...,NV,2021-02-24 15:55:10,1993-01-06,2021-05-03 18:03:58,2021-05-03,SCHPMT,P2P_COMMIT,P2P,2021-05-03,Non-Fraud
1,65.19,0.00,45,5,2721,NaT,charter communications,southwest,california,MOBL,...,CA,NaT,1971-01-07,2021-01-13 19:19:37,2021-01-13,SCHPMT,P2P_COMMIT,P2P,2021-01-13,Non-Fraud
2,54.84,34570.63,36,8,1531,2021-12-22 10:42:51,utah broadband llc,mountain,utah,ONLN,...,MD,2019-05-05 01:08:39,1994-02-01,2021-04-08 09:42:51,2021-04-08,SCHPMT,P2P_COMMIT,P2P,2021-04-08,Fraud
3,0.01,0.00,62,3,835,2020-02-08 07:28:31,t-mobile usa inc.,southwest,california,MOBL,...,NV,2019-02-16 06:45:37,2001-11-01,2021-08-10 15:28:31,2021-08-10,SCHPMT,P2P_COMMIT,P2P,2021-08-10,Non-Fraud
4,497.08,12725.18,81,2,1095,2020-12-28 12:12:44,cogent communications,south central,texas,MOBL,...,UT,2020-05-08 10:27:06,1987-02-07,2021-06-27 11:12:44,2021-06-27,SCHPMT,P2P_COMMIT,P2P,2021-06-27,Fraud

In [9]:
to_categorical = ['CARR_NAME', 'RGN_NAME', 'STATE_PRVNC_TXT', 'ALERT_TRGR_CD',
                  'DVC_TYPE_TXT', 'AUTHC_PRIM_TYPE_CD', 'AUTHC_SCNDRY_STAT_TXT',
                  'CUST_STATE','ACTN_CD','ACTN_INTNL_TXT','TRAN_TYPE_CD',
                  'FRAUD_NONFRAUD']

for category in to_categorical:
  trainDf[category] = trainDf[category].astype("category")

In [10]:
trainDf.describe()

,TRAN_AMT,ACCT_PRE_TRAN_AVAIL_BAL,CUST_AGE,OPEN_ACCT_CT,WF_dvc_age,CUST_ZIP
count,14000.000000,14000.000000,14000.000000,14000.000000,14000.000000,14000.000000
mean,275.377747,10233.110609,53.937214,6.666714,611.061571,74007.681071
std,317.892333,29967.453812,18.829836,9.059419,668.113489,24948.053588
min,0.010000,0.000000,13.000000,0.000000,-117.000000,0.000000
25%,11.322500,0.000000,39.000000,3.000000,75.000000,63123.000000
50%,161.355000,2410.395000,59.000000,5.000000,365.500000,85037.000000
75%,488.822500,4732.695000,68.000000,7.000000,961.000000,92201.000000
max,2376.060000,361519.050000,105.000000,227.000000,2783.000000,99835.000000

In [16]:
#Visualize unique items in each categorical variable and 

for category in to_categorical:
  print("Category: " + category)
  print("nunique: " + str(trainDf[category].nunique()))
  print("----- Top -----")
  print(trainDf[category].value_counts())
  print("-------------------------------")

Category: CARR_NAME
nunique: 554
----- Top -----
cox communications inc.                                   1278
t-mobile usa  inc.                                        1146
charter communications inc                                1145
comcast                                                   1063
comcast cable communications  llc                          892
                                                          ...
project mutual telephone cooperative association  inc.       1
radiomovil dipsa  s.a. de c.v.                               1
blacknight internet solutions limited                        1
riverside county office of education                         1
meeker cooperative light & power association                 1
Name: CARR_NAME, Length: 554, dtype: int64
-------------------------------
Category: RGN_NAME
nunique: 19
----- Top -----
southwest              7123
south central          1346
southeast               572
mountain                467
northeast               419
great lakes             360
mid atlantic            301
pacific northwest       256
unknown                 241
midwest                 184
pacific                   9
south east                3
ile-de-france             3
pays de la loire          2
central canada            1
comunidad de madrid       1
north west                1
leinster                  1
west coast                1
Name: RGN_NAME, dtype: int64
-------------------------------
Category: STATE_PRVNC_TXT
nunique: 127
----- Top -----
california             5438
arizona                1235
texas                  1234
nevada                  450
new york                369
                       ...
nordrhein-westfalen       1
san salvador              1
nueva esparta             1
ontario                   1
`amman                    1
Name: STATE_PRVNC_TXT, Length: 127, dtype: int64
-------------------------------
Category: ALERT_TRGR_CD
nunique: 2
----- Top -----
MOBL    7110
ONLN    6890
Name: ALERT_TRGR_CD, dtype: int64
-------------------------------
Category: DVC_TYPE_TXT
nunique: 4
----- Top -----
MOBILE     8796
DESKTOP    2986
TABLET      238
PHONE       219
Name: DVC_TYPE_TXT, dtype: int64
-------------------------------
Category: AUTHC_PRIM_TYPE_CD
nunique: 5
----- Top -----
UN_PWD      10536
FACE_ID      1953
AFA_PL        720
TOUCH_ID      701
AFA_BM         90
Name: AUTHC_PRIM_TYPE_CD, dtype: int64
-------------------------------
Category: AUTHC_SCNDRY_STAT_TXT
nunique: 3
----- Top -----
ALLOW                13193
CHALLENGE_SUCCESS      646
CHALLENGE_ISSUED        87
Name: AUTHC_SCNDRY_STAT_TXT, dtype: int64
-------------------------------
Category: CUST_STATE
nunique: 48
----- Top -----
CA    4570
TX    2368
AZ    1288
FL     914
NV     535
CO     477
MN     452
GA     304
OR     222
WA     222
NJ     215
NM     205
NC     179
UT     171
NY     156
VA     139
ID     124
SC     111
PA     110
IA     109
IL      98
WI      97
NE      94
MD      89
MT      79
SD      76
AK      71
AL      55
TN      51
CT      47
MO      44
WY      32
OH      26
MS      24
DE      24
MI      23
ND      22
KS      22
LA      20
IN      19
OK      16
DC      16
HI      13
AR      13
KY       8
ME       5
WV       5
GU       4
Name: CUST_STATE, dtype: int64
-------------------------------
Category: ACTN_CD

KeyError: 'ACTN_CD'

In [12]:
trainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TRAN_AMT                 14000 non-null  float64
 1   ACCT_PRE_TRAN_AVAIL_BAL  14000 non-null  float64
 2   CUST_AGE                 14000 non-null  int64
 3   OPEN_ACCT_CT             14000 non-null  int64
 4   WF_dvc_age               14000 non-null  int64
 5   PWD_UPDT_TS              10868 non-null  datetime64[ns]
 6   CARR_NAME                11291 non-null  category
 7   RGN_NAME                 11291 non-null  category
 8   STATE_PRVNC_TXT          11291 non-null  category
 9   ALERT_TRGR_CD            14000 non-null  category
 10  DVC_TYPE_TXT             12239 non-null  category
 11  AUTHC_PRIM_TYPE_CD       14000 non-null  category
 12  AUTHC_SCNDRY_STAT_TXT    13926 non-null  category
 13  CUST_ZIP                 14000 non-null  int64
 14  CUST_STATE               13964 non-null  category
 15  PH_NUM_UPDT_TS           6437 non-null   datetime64[ns]
 16  CUST_SINCE_DT            14000 non-null  datetime64[ns]
 17  TRAN_TS                  14000 non-null  datetime64[ns]
 18  TRAN_DT                  14000 non-null  datetime64[ns]
 19  ACTN_CD                  14000 non-null  category
 20  ACTN_INTNL_TXT           14000 non-null  category
 21  TRAN_TYPE_CD             14000 non-null  category
 22  ACTVY_DT                 14000 non-null  datetime64[ns]
 23  FRAUD_NONFRAUD           14000 non-null  category
dtypes: category(12), datetime64[ns](6), float64(2), int64(4)
memory usage: 1.5 MB

In [13]:
#Checking if ACTVY_DT is redudant, since nrow=14k, they are.
sum(trainDf['TRAN_DT'] == trainDf['ACTVY_DT'])

14000

In [14]:
redundant = ['ACTN_CD', 'TRAN_TYPE_CD','ACTN_INTNL_TXT','ACTVY_DT']
trainDf.drop(columns = redundant, inplace=True)

In [15]:
trainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TRAN_AMT                 14000 non-null  float64
 1   ACCT_PRE_TRAN_AVAIL_BAL  14000 non-null  float64
 2   CUST_AGE                 14000 non-null  int64
 3   OPEN_ACCT_CT             14000 non-null  int64
 4   WF_dvc_age               14000 non-null  int64
 5   PWD_UPDT_TS              10868 non-null  datetime64[ns]
 6   CARR_NAME                11291 non-null  category
 7   RGN_NAME                 11291 non-null  category
 8   STATE_PRVNC_TXT          11291 non-null  category
 9   ALERT_TRGR_CD            14000 non-null  category
 10  DVC_TYPE_TXT             12239 non-null  category
 11  AUTHC_PRIM_TYPE_CD       14000 non-null  category
 12  AUTHC_SCNDRY_STAT_TXT    13926 non-null  category
 13  CUST_ZIP                 14000 non-null  int64
 14  CUST_STATE               13964 non-null  category
 15  PH_NUM_UPDT_TS           6437 non-null   datetime64[ns]
 16  CUST_SINCE_DT            14000 non-null  datetime64[ns]
 17  TRAN_TS                  14000 non-null  datetime64[ns]
 18  TRAN_DT                  14000 non-null  datetime64[ns]
 19  FRAUD_NONFRAUD           14000 non-null  category
dtypes: category(9), datetime64[ns](5), float64(2), int64(4)
memory usage: 1.3 MB

###Codebook

TRAN_AMT
  - Transaction Amount (How much did they try to withdraw)

ACCT_PRE_TRAN_AVAIL_BAL
  - Account Pre-Transaction available balance

CUST_AGE
  - Customer age

OPEN_ACCT_CT
  - (?) Open account count

WF_dvc_age
  - ???

PWD_UPDT_TS
  - ??? Update Timestamp, last time password updated?

CARR_NAME
  - Carrier Name

RGN_NAME
  - Region Name

STATE_PRVNC_TXT
  - State Province Text (Origin of text?)

ALERT_TRGR_CD
  - Alert Trigger ???

DVC_TYPE_TXT
  - Device Type Text (Type of device used to send text)

AUTHC_PRIM_TYPE_CD
  - Authentication Primary Type (FaceId, TouchId, etc.)

AUTHC_SCNDRY_STAT_TXT
  - Authentication secondary status text (Allow, Challenge Success, Challenge Issued)

CUST_ZIP
  - Customer ZIP

CUST_STATE
  - Customer State

PH_NUM_UPDT_TS
  - Phone number update timestamp (Time since last phone number change)

CUST_SINCE_DT
  - Customer since date

TRAN_TS
  - Transcation Timestamp

TRAN_DT
  - Transaction Date (Subset of timestamp)

Good Links:

What is elder fraud?:
https://www.fbi.gov/scams-and-safety/common-scams-and-crimes/elder-fraud

More elaboration on the types of elder fraud:
https://www.comparitech.com/blog/information-security/elder-fraud/

Leads for feature engineering
- Binary check to see if customer state matches transaction state
- Convert all dates to normalize against current date
- And/or convert dates to normalize against customer signup
- Day of the week feature
- Percentage of account balance

- ZIP/State code features? Education level/Rural/Urban levels of zip code
-